version: '3.8'

services:
  flask_service:
    image: ghcr.io/rsalas6/my_flask_microservice-prod:latest
    ports:
      - "5000:5000"
    networks:
      - app_network

  fastapi_service:
    image: ghcr.io/rsalas6/my_fastapi_microservice-prod:latest
    ports:
      - "5001:5001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
