version: '3'

# Definición de las variables
vars:
  app_name: my_fastapi_microservice
  app_source: .
  container_workdir: /app
  github_username: rsalas6
  image_repo: ghcr.io/{{.github_username}}/{{.app_name}}

# Definición de las tareas
tasks:
  dev:build:
    desc: Construir la imagen de Docker para desarrollo
    cmds:
      - docker build -f Dockerfile.dev -t {{.image_repo}}-dev .

  dev:run:
    desc: Ejecutar el contenedor de Docker en modo desarrollo con recarga automática
    cmds:
      - docker run --rm -p 5001:5001 -v {{.app_source}}:{{.container_workdir}} {{.image_repo}}-dev

  prod:build:
    desc: Construir la imagen de Docker para producción
    cmds:
      - docker build -f Dockerfile.prod -t {{.image_repo}}-prod .

  prod:run:
    desc: Ejecutar el contenedor de Docker en modo producción
    cmds:
      - docker run --rm -p 5001:5001 {{.image_repo}}-prod

  clean:
    desc: Eliminar las imágenes de Docker
    cmds:
      - docker rmi {{.image_repo}}-dev || true
      - docker rmi {{.image_repo}}-prod || true

  dev:publish:
    desc: Publicar la imagen de desarrollo en GitHub Container Registry
    cmds:
      - echo $CR_PAT | docker login ghcr.io -u {{.github_username}} --password-stdin
      - docker push {{.image_repo}}-dev

  prod:publish:
    desc: Publicar la imagen de producción en GitHub Container Registry
    cmds:
      - echo $CR_PAT | docker login ghcr.io -u {{.github_username}} --password-stdin
      - docker push {{.image_repo}}-prod
