version: '3'

# Definición de las variables
vars:
  app_name: my_flask_microservice
  app_source: .
  container_workdir: /app
  flask_debug: 'true'

# Definición de las tareas
tasks:
  build-dev:
    desc: Construir la imagen de Docker para desarrollo
    cmds:
      - docker build -f Dockerfile.dev -t {{.app_name}}-dev .

  build-prod:
    desc: Construir la imagen de Docker para producción
    cmds:
      - docker build -f Dockerfile.prod -t {{.app_name}}-prod .

  run-dev:
    desc: Ejecutar el contenedor de Docker en modo desarrollo
    cmds:
      - docker run --rm -p 5000:5000 -v {{.app_source}}:{{.container_workdir}} -e FLASK_DEBUG={{.flask_debug}} {{.app_name}}-dev

  run-prod:
    desc: Ejecutar el contenedor de Docker en modo producción
    cmds:
      - docker run --rm -p 5000:5000 -e FLASK_DEBUG={{.flask_debug}} {{.app_name}}-prod

  clean:
    desc: Eliminar las imágenes de Docker
    cmds:
      - docker rmi {{.app_name}}-dev || true
      - docker rmi {{.app_name}}-prod || true

  push:
    desc: Push de las imágenes al registry de Docker
    cmds:
      - docker tag {{.app_name}}-prod myregistry.com/{{.app_name}}-prod
      - docker push myregistry.com/{{.app_name}}-prod

  # Tarea para setear una variable en runtime si es necesario
  set-app-name:
    desc: Establecer el nombre de la aplicación
    vars:
      app_name: '{{default "my_flask_microservice" .APP_NAME}}'

# Si se necesita cambiar el nombre de la aplicación en runtime se puede correr:
# task set-app-name -- APP_NAME=nuevo_nombre && task build
